import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/dp-2.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { DownloadIcon, LinkArrow, RightIcon } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>John Martin Gasangue</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="JohnMartin" className='w-[85%] h-auto lg:hidden md:inline-block md:w-full' priority sizes="(max-width: 768px) 100vw, (max-width: 1200px) 100vw, 100vw"/>
            </div>
            <div className='w-1/2 flex flex-col items-left self-center lg:w-full lg:text-center'>
              <AnimatedText text="Hello World! I'm" className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <AnimatedText text="John Martin Gasangue" className='!text-5xl !text-left xl:!text-4xl lg:!text-center lg:!text-5xl md:!text-4xl sm:!text-2xl' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                A Software Developer and aspiring Web Developer based in Bacoor City, Cavite, Philippines.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/Gasangue, John Martin.pdf" target={"_blank"} className="flex items-center bg-dark text-light p-2.5 px-6 rounded-3xl text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base sm:text-xs" download={true}>
                  My Resume <DownloadIcon className={`w-4 xl:w-4 ml-3 sm:w-3 sm:ml-1`}/>
                </Link>
                <Link href="/projects" className="flex items-center bg-light text-dark p-2.5 px-6 mx-5 rounded-3xl text-lg font-semibold hover:bg-dark hover:text-light border-2 border-dark hover:border-dark dark:bg-dark dark:text-light dark:border-2 dark:border-light hover:dark:bg-light hover:dark:text-dark hover:dark:border-light md:p-2 md:px-4 md:text-base sm:text-xs">
                  See My Works <RightIcon className={`w-4 xl:w-4 ml-3 sm:w-3 sm:ml-1`}/>
                </Link>
                {/* <Link href="jmgasangue@gmail.com" target={"_blank"} className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">
                  Contact
                </Link> */}
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        {/* recent works showcase in a marquee */}
        {/* recent certificates */}
        {/* get in touch/contact or button to contact page */}
        {/* reference: https://dennissnellenberg.com */}
      </main>
    </>
  )
}
